config/routes.rb
Rails.application.routes.draw do
  root to: "spendings#index"

  resources :spendings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spending.rb
class Spending < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  before_action :set_spending, only: [:show, :edit, :update, :destroy]

  # GET /spendings
  # GET /spendings.json
  def index
    @spendings = Spending.all
  end

  # GET /spendings/1
  # GET /spendings/1.json
  def show
  end

  # GET /spendings/new
  def new
    @spending = Spending.new
  end

  # GET /spendings/1/edit
  def edit
  end

  # POST /spendings
  # POST /spendings.json
  def create
    @spending = Spending.new(spending_params)

    respond_to do |format|
      if @spending.save
        format.html { redirect_to @spending, notice: 'Spending was successfully created.' }
        format.json { render :show, status: :created, location: @spending }
      else
        format.html { render :new }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spendings/1
  # PATCH/PUT /spendings/1.json
  def update
    respond_to do |format|
      if @spending.update(spending_params)
        format.html { redirect_to @spending, notice: 'Spending was successfully updated.' }
        format.json { render :show, status: :ok, location: @spending }
      else
        format.html { render :edit }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spendings/1
  # DELETE /spendings/1.json
  def destroy
    @spending.destroy
    respond_to do |format|
      format.html { redirect_to spendings_url, notice: 'Spending was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spending
      @spending = Spending.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spending_params
      params.require(:spending).permit(:spending_date, :description, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuraganTakoyaki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spendings/_form.html.erb
<%= form_with(model: spending, local: true) do |form| %>
  <% if spending.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spending.errors.count, "error") %> prohibited this spending from being saved:</h2>

      <ul>
      <% spending.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :spending_date %>
    <%= form.date_select :spending_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spendings/edit.html.erb
<h1>Editing Spending</h1>

<%= render 'form', spending: @spending %>

<%= link_to 'Show', @spending %> |
<%= link_to 'Back', spendings_path %>

app/views/spendings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spendings</h1>

<table>
  <thead>
    <tr>
      <th>Spending date</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spendings.each do |spending| %>
      <tr>
        <td><%= spending.spending_date %></td>
        <td><%= spending.description %></td>
        <td><%= spending.amount %></td>
        <td><%= link_to 'Show', spending %></td>
        <td><%= link_to 'Edit', edit_spending_path(spending) %></td>
        <td><%= link_to 'Destroy', spending, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spending', new_spending_path %>

app/views/spendings/new.html.erb
<h1>New Spending</h1>

<%= render 'form', spending: @spending %>

<%= link_to 'Back', spendings_path %>

app/views/spendings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spending date:</strong>
  <%= @spending.spending_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spending.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @spending.amount %>
</p>

<%= link_to 'Edit', edit_spending_path(@spending) %> |
<%= link_to 'Back', spendings_path %>